version: '3.7'

services:
  frontend:
    image: node:16
    working_dir: /app
    env_file: .env
    environment:
      - PORT=3333
    ports:
      - 3333:3333
    volumes:
      - ./:/app
    command: sh -c "yarn && yarn build && yarn start"
